/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OpportunityHubRouteImport } from './routes/opportunity-hub'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InternshipProgramRouteImport } from './routes/internship-program'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const VolunteerLazyRouteImport = createFileRoute('/volunteer')()

const VolunteerLazyRoute = VolunteerLazyRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/volunteer.lazy').then((d) => d.Route))
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/vision-mission.lazy').then((d) => d.Route),
)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/success-stories.lazy').then((d) => d.Route),
)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityHubRoute = OpportunityHubRouteImport.update({
  id: '/opportunity-hub',
  path: '/opportunity-hub',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/opportunity-hub.lazy').then((d) => d.Route),
)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/leaderboard.lazy').then((d) => d.Route))
const InternshipProgramRoute = InternshipProgramRouteImport.update({
  id: '/internship-program',
  path: '/internship-program',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/internship-program.lazy').then((d) => d.Route),
)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/gallery.lazy').then((d) => d.Route))
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events.lazy').then((d) => d.Route))
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/internship-program': typeof InternshipProgramRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunity-hub': typeof OpportunityHubRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/vision-mission': typeof VisionMissionRoute
  '/volunteer': typeof VolunteerLazyRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/internship-program': typeof InternshipProgramRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunity-hub': typeof OpportunityHubRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/vision-mission': typeof VisionMissionRoute
  '/volunteer': typeof VolunteerLazyRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/internship-program': typeof InternshipProgramRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunity-hub': typeof OpportunityHubRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/vision-mission': typeof VisionMissionRoute
  '/volunteer': typeof VolunteerLazyRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/events'
    | '/gallery'
    | '/internship-program'
    | '/leaderboard'
    | '/opportunity-hub'
    | '/programs'
    | '/success-stories'
    | '/vision-mission'
    | '/volunteer'
    | '/blogs/$slug'
    | '/programs/$slug'
    | '/blogs/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/gallery'
    | '/internship-program'
    | '/leaderboard'
    | '/opportunity-hub'
    | '/success-stories'
    | '/vision-mission'
    | '/volunteer'
    | '/blogs/$slug'
    | '/programs/$slug'
    | '/blogs'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/events'
    | '/gallery'
    | '/internship-program'
    | '/leaderboard'
    | '/opportunity-hub'
    | '/programs'
    | '/success-stories'
    | '/vision-mission'
    | '/volunteer'
    | '/blogs/$slug'
    | '/programs/$slug'
    | '/blogs/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  InternshipProgramRoute: typeof InternshipProgramRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OpportunityHubRoute: typeof OpportunityHubRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  VisionMissionRoute: typeof VisionMissionRoute
  VolunteerLazyRoute: typeof VolunteerLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity-hub': {
      id: '/opportunity-hub'
      path: '/opportunity-hub'
      fullPath: '/opportunity-hub'
      preLoaderRoute: typeof OpportunityHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship-program': {
      id: '/internship-program'
      path: '/internship-program'
      fullPath: '/internship-program'
      preLoaderRoute: typeof InternshipProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  InternshipProgramRoute: InternshipProgramRoute,
  LeaderboardRoute: LeaderboardRoute,
  OpportunityHubRoute: OpportunityHubRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SuccessStoriesRoute: SuccessStoriesRoute,
  VisionMissionRoute: VisionMissionRoute,
  VolunteerLazyRoute: VolunteerLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
